### ISSUE TITLE
Unable to turn off debug

### ISSUE THREAD

**Issue by garadox** [ipedrazas/drone-helm#13]
I've tried not setting `debug` at all in the drone.yml, i've tried setting `debug: false` and i've tried `debug: null`. 

Every time the plugin runs it echo's all the environment vars and I'm not sure how to turn that off. Please help!

**Comment by ipedrazas** [comment]
which version of the plugin are you running?

**Comment by garadox** [comment]
I just pulled the latest image and tested again, and I still see `-Var:-- XXX=YYY` for all the environment vars in the output.

**Comment by ipedrazas** [comment]
You were absolutely right. I've just pushed a new image. I'll do some testing and report back! 🙌

**Comment by ipedrazas** [comment]
Latest build fixes this problem. thanks!
