### ISSUE TITLE
`add repo` missing

### ISSUE THREAD

**Issue by ipedrazas** [ipedrazas/drone-helm#21]
There's no option to add a custom repo.

**Comment by so0k** [comment]
Oops, didn't notice there was an outstanding issue on this - https://github.com/ipedrazas/drone-helm/pull/41

The problem is, I was convinced it needed to be a list of repositories and after completing everything.. I feel there's no point in supporting a list of repositories?

**Comment by ipedrazas** [comment]
https://github.com/ipedrazas/drone-helm/pull/41 fixes this
