### ISSUE TITLE
register with plugins.drone.io

### ISSUE THREAD

**Issue by bradrydzewski** [ipedrazas/drone-helm#5]
It would be great to include this in the newly created plugin registry. I'm happy to help if you have any questions. http://readme.drone.io/tutorials/how-to-register-a-plugin/

**Comment by ipedrazas** [comment]
I'm refactoring it a bit to make it more user-friendly, but I'll register it as soon as it's good to use 😄

**Comment by ipedrazas** [comment]
Planned for this week
